apiVersion: v1
kind: Service
metadata:
  name: continental-backend-service
spec:
  selector:
    app: conti
    tier: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: continental-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conti
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: conti
        tier: backend
        track: stable
    spec:
      containers:
      - name: backend
        image: continental-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          value: continental
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: continental
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_HOST
          value: continental-database-service